// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF7OtyI193E2hPU0S1ACmcE5AO-xH8OIE',
    appId: '1:633364646650:web:7b6a4386704f25b5f61743',
    messagingSenderId: '633364646650',
    projectId: 'event-alerts-d6766',
    authDomain: 'event-alerts-d6766.firebaseapp.com',
    storageBucket: 'event-alerts-d6766.firebasestorage.app',
    measurementId: 'G-QBRKHV66TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhccy_iwKO-itJ8Jp4IHdCGaQ6bEWpApY',
    appId: '1:633364646650:android:2240e3ee8485b43ef61743',
    messagingSenderId: '633364646650',
    projectId: 'event-alerts-d6766',
    storageBucket: 'event-alerts-d6766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2sb4QWU5-Gs9sqioBUn3m_LnWPYP9Lf8',
    appId: '1:633364646650:ios:85b555a6786369b2f61743',
    messagingSenderId: '633364646650',
    projectId: 'event-alerts-d6766',
    storageBucket: 'event-alerts-d6766.firebasestorage.app',
    iosBundleId: 'com.example.eventAlerts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2sb4QWU5-Gs9sqioBUn3m_LnWPYP9Lf8',
    appId: '1:633364646650:ios:85b555a6786369b2f61743',
    messagingSenderId: '633364646650',
    projectId: 'event-alerts-d6766',
    storageBucket: 'event-alerts-d6766.firebasestorage.app',
    iosBundleId: 'com.example.eventAlerts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF7OtyI193E2hPU0S1ACmcE5AO-xH8OIE',
    appId: '1:633364646650:web:8ec991c5c3b8ed9bf61743',
    messagingSenderId: '633364646650',
    projectId: 'event-alerts-d6766',
    authDomain: 'event-alerts-d6766.firebaseapp.com',
    storageBucket: 'event-alerts-d6766.firebasestorage.app',
    measurementId: 'G-47EGW5HMZG',
  );
}
